#+TITLE: MY INBOX

* 2024
** 2024-05 May
*** 2024-05-02 Thursday
**** TODO A workspace for learning :ideas:

Combines wikipedia, dictionary, flashcards, mind mapping into a fun experience
Added: [2024-05-02 Thu 11:59]

*** 2024-05-09 Thursday
**** NOTE Type Level Typescript :learning:

+ TypeScript provides us with 5 main categories of types: primitive types, literal types, data structure types,
  union types, and intersection types.
+ To get a better grasp of unions and intersections types, I'll need to cover a notion that's fundamental to Type-level TypeScript:
  all types are sets. 
+ "unknown" is the top-level type set to which all other types belong
+ "never" is the empty, bottom-level set, for example when trying to intersect `string` and `number` 
Added: [2024-05-09 Thu 15:03]

* Entropy

Entropy is the amount of disorder in a system. Negative entropy means that something is becoming less disordered. In order for something to become less disordered, energy must be used. This will not occur spontaneously. A messy, or disordered, room will not become clean, or less disordered, on its own.

* Woven

A generative AI based social network 

* Mind palace

Bed
Shoes
Dresser
Lights
Door

Plant
Kendama wall
Chaise
Desk
Bookshelf 

* The many facets of being a leader in tech

It's not always technical. Likeability, visibility, and a growth mindset play a role. Luck plays a role. 

* I have a fixed morning *and* evening routine. As well as a set of weekly, monthly, and annual routines.  MORNING:  * Check messages. * Exercise in home gym; listen to podcasts. * Review the day's plan and adjust as needed, over coffee and light breakfast.  EVENING:  * Reschedule day's unfinished tasks. * Reflect on the day and record observations in Obsidian daily note. * Evening reading time (wind-down, no electronics). * Night prayers.  WEEKLY (Sunday evening):  * Write a short (250- to 750-word narrative) summarizing the prior week, in Obsidian.  * Plan tasks by day for upcoming week. * Household chores (cleaning, laundry, watering plants).  MONTHLY:  * Log upcoming bills in Todoist (the Finance project). * Plan bigger/multi-step projects on the calendar for the coming month (last day of month). * Execute the "every month" tasks (Saturday closest to the 15th) -- stuff like recharge emergency batteries, review shopping lists, &c.  ANNUAL:  * Review my personal life roadmap, on 7/4 and 12/25 of each year.
