baseURL = "https://darrellbanks.com/"
languageCode = "en-us"
title = "DB"
theme = "stack"

[params]
mainSections = ['posts']

[params.sidebar.avatar]
enabled = true
local = false
src = 'https://avatars.githubusercontent.com/u/1380897?v=4'

[[widgets.homepage]]
type = "tag-cloud"

[[widgets.homepage.params]]
limit = 10