baseURL = "https://darrellbanks.com/"
languageCode = "en-us"
title = "Darrell's Braindump"
theme = "hugo-kiera"

[params]
date_format = "02 Jan 2006"
tagline = "I sometimes write things. They sometimes end up here."
email = "hacknightly@gmail.com"

[author]
    name = "Darrell Banks"
    github = "hacknightly"
    gitlab = ""
    linkedin = "darrell-banks-13058621"      
    facebook = "" 
    twitter = ""   
    instagram = "skippysodrippy"
    stackoverflow = "users/541098/hacknightly"
    devto = ""