baseURL = "https://darrellbanks.com/"
languageCode = "en-us"
title = "DB"
theme = "stack"

[params.sidebar.avatar]
enabled = true
local = false
src = 'https://avatars.githubusercontent.com/u/1380897?v=4'