# Beats to consider
https://www.youtube.com/watch?v=ZA_GwDPaA9k
https://www.youtube.com/watch?v=00GlSwklGf4
# Fine
https://www.youtube.com/watch?v=rp6kA3AEzhc
I been through some things,
but that aint on my mind,
focused on my change,
I been on my grind,
mama called me crying,
said she got a sign,
from the lord up above,
he said everything is fine,
don't you worry about thing,
take your pain, make it mine.
spread your light around the world,
make it rain,
let it shine.

# Mo Dollaz
https://www.youtube.com/watch?v=gV7xr6GRsxk
Money Motivated.
I need everything and more, gold plated.


I. Need. Mo Dollaz.
Nothing else makes sense to me.
It's a part of my history.


# Got it all
https://www.youtube.com/watch?v=acTw7cFLg0k
Got it all, livin' like I don't,
make me wanna go and get it when they say I won't,

cuz I - know I can,
it's all in the plan,

saw the future in my palm, got in my hand,
underground king now niggas understand,
started from the dirt, now I'm in the sand.

damn - vacation's nice

I touch studio and we make heat,
I ball hard nigga nba street.

https://www.youtube.com/watch?v=J1Xz4KaibCg&list=RDrp6kA3AEzhc&index=9
Back when I was broke they would treat me like a joke,
ha ha, now I be like bah bah, niggas treat me like the goat.

And I don't say that to gloat nope,
really ya'll the got no hope,
I be up in this laboratory cookin dope dope,

money was slowpoke now it comes oh so
fast

https://www.youtube.com/watch?v=pdYJtRBPlTw&list=RDrp 6kA3AEzhc&index=12
I heard you got that fire,
please be my supplier,
I heard you got that dope,
girl you super dope,

Hey Misses,
dope dealer would ya,
gimme some of that good could ya,
I been feinin' for it for minute,
and it look so good,
and I heard you cook so good,
I heard you could hook whole hoods wit that thang you slang,
but you curve em like corners they the same ol same,
I know you was different you was never plain ol jane,
know you want the finer things and it ain't no shame,


https://www.youtube.com/watch?v=bp_hIN-88gY
uh, yeah, uh, yeah

Yao Ming

flow like water - watch a nigga swim,
I been, ballin so hard I'ma need a bigger gym,
I mean, they say they ballin they barely hit the rim,
I'm seein, W's nigga really I'm flippin M's,
dividends sit me in a sicker benz,
they ain't never seen that, that shit look like it's pretend,
that's a big expense but I didn't check my balance,
whatever I spends, I get it back with my talents,
I pick up this pen and it's over for these rap guys, geez.
ain't even have to use half my steez.
stacks like these come with enemies
gotta nigga askin where is the love? black eyed peas.
I'm finesse and they lack my ease,
I'm the best that's a scientific fact, cite me.
I wrote it I quoted myself,
was broke, no wallet, now they notice my belt.
no job, no car now they notice my whip,
see I came far but I know dis not it -
niggas pop lips,
but they never drop hits,
I don't know about that,
but I know it's not this.

now my whole team lookin like a ball team,
money tall like yao ming,
pilin' up around me,



now my whole team lookin' like a ball team,
man they used to doubt me,
money tall like yao ming,
piling up around me,


https://www.youtube.com/watch?v=CcgoIl7QORc

I been on some real fuck you shit lately,
takes me back to days when they would pay me,
no attention only cuz my flow is in a totally different solar system,
not a human being I told these niggas I must be a different organism,
they say damn they soul is him,

I just guess I'm colder than them,
so the miniminum temperature around here, is me
no lower then him,

my wrist is frozen,
my neck is frozen,
my check is loaded with ze - roes.
I'm ballin like free - throws
caught charges I beat - those.
they ride waves like speed - boat.
I stop waves like sea - sho's.
they not in my league - so.
I don't play no games, wit em.
This shit feel like cheat - codes.
hope they know that these ropes,
won't loosen on these throats,
do not try to hang - wit em.
I suggest that you watch the best,
and try to process how I finesse.
cuz it's not a question of if I'm gon kill shit,
it's more like how agressive.



https://www.youtube.com/watch?v=pdYJtRBPlTw

Fast

Say you love me -
I don't believe it -
I'm too fast now -
that's not a secret.
yeah I know you think about me every time I go,
you think we could be together and be fine, I know

I know, I know you need something more,
you ambitious I see what you lookin for,
you want someone that's gon come back home and hold you,
you want someone that's gon feel like your support,
I know I can't be that person that's for certain,
way too busy on my grizzly out here workin,
I know you hurtin -


https://www.youtube.com/watch?v=3HRSGT3NeXs

Yeah Yeah,
Feelin like the mawfuckin man,
I don't really understand shit,
but money in my hand,
god damn.
Who that is? What they sayin?
Really we don't give a fuck less
they talkin bout payin

Yeah whoa -
this that dope.
this that fire.

* Go Hard
https://www.youtube.com/watch?v=sCxTYDOKkug

Tell me how you really feel about me -
If you round me nigga keep it real about me,
cuz I don't got time for the fake shit,
Whole squad go hard we'll break shit.

x2
Whole squad go hard everyday shit.

Yeah we go,
super hard, super hard
look like Paul with the charge,

she said what you call that, told it's a car.
we don't ride the wave, but you swimmin with you sharks.

I'm not lookin for your heart girl,
I'm lookin at the charts.

damn it look like my time,
you know stars only shine in the night time,
say you got some niggas wit you they ain't like mine,
you not in your right mind, you gon need a lifeline.
if you call my phone then you talkin on a priceline.
what you tryna buy?
don't sell birds but I'm looking kinda fly,
so them hoes gon flock for the guy,
she grease that, make it pop, make it fry.
i heat that, make it hot like July.
your new shit I peeped that it flopped, this is why.
that shit don't feel like this,
man it's been a long time and I'm still like this.

chorus x 2

super hard, super hard,
like my dogs on the yard,
they ain't comin home
but the squad play they part,
so of course it is still all business,
sign dotted lines so the deals all finished.
had to keep it real, so I'm still authentic,
now my whip too fast liquor spilled all in it,
if it's bout money it's a deal I'm wit it,
but if you owe it to me, I will come get it.
custom, bussdown feel so fitted.
how she got no followers and still so pretty?
she loves the city, feels so philly.
we ain't finna stop till the bills go billy,
but in the meantime got my wrist on chilly,
I got on these niggas heels quick, a-chilles.
guess they not built like this
man it's been a long time and I'm still like this

https://www.youtube.com/watch?v=fp1_DCBJfBw
When we in the spot, it goes down.
Got enough money to go round.
they know what we do but don't know how.
all they know is we ain't gon slow down.
slow down.
slow down.
slow down.
she gon' speed it up, then slow down.
slow down
slow down
slow down.
bet the money still come fast.

cash - I don't do no IOU.
big racks - you should see the stacks I go through.
need max I don't really do splits,
who's this? he slaps.
make a bitch need knee pads.


see me spaz

eye on you.
I won't do.


https://www.youtube.com/watch?v=v68lDoTkIt0
Goodbye pain
my mother's from a place where like 4 percent make it out,
but she always believed in her chances of breaking out,
she said I won't raise my son here,
don't know where I'm going but promise I'm going somewhere,
we'll see what I become there.
a blessin cuz my dad and my uncle used to run there,
like they was both invincible long as they had a gun near,
so one year she packed us all up, and we was gone.
Told us all we have is just us, now this is home.
uncle was like 13, I think I was 3,
but I could tell he was hurting,
all he knew was the streets,
and my daddy was the same,
all they knew was the game,
all they knew was the city,
all this new shit is strange,
and it came out in different ways for em,
uncle left home,
mom prayed for him,
dad's alcohol problem really start to heat up,
now every time he mad at mom, she get beat up.


you can't hurt me no mo.
you can't hurt me no mo.

so she's teh one that told me there's always a different route.


https://www.youtube.com/watch?v=MduEHNMSBHo

Yeah I be workin'
You know I be workin
But I can make time for you.
I can make time for you tonight.
You know I be workin.
You know I be workinnnnn yeah -
but I can make time for you.
I can make time for you tonight.

But I gotta grind right now,
even though you on my mind right now,
I promise when I get out I'ma ride,
to your home base like slide,

* Seen Too Much
https://www.youtube.com/watch?v=oGFPHlxu02U

I done seen too much,
hear these niggas talkin that don't mean too much,
going for the win man my team too clutch,
we don't fuck with the niggas that you seem to trust,

yeah - cuz my circle so small,
I hit the plug got purple on call,
know about me, not certain bout y'all,
ya'll chasin these hoes stead of workin on flaws,
on God we aint' never on pause,

* Perfect
https://www.youtube.com/watch?v=GdKEdN66jUc
She say she love me,
I don't believe it,
I'm chasin money girl that's not a secret,
everything i got up outta the mud,
I don't need your love,
you go head and keep it.
might try to fuck when I get the time,
but my time is money so please don't expect it.
this ain't no luck, it's all by design,
everything I do I gotta perfect it.

uh -

* Movie Star
https://www.youtube.com/watch?v=d3VyCV-uli4
We go back and forth about who we are,
I act like I'm the god,
you act like movie star,
I pretend like that shit doesn't phase me,
maybe,
we just drive each other fucking crazy,
baby,
cash money makin is my hobby so I be,
on my grind early like some coffee,

* Sober
  https://www.youtube.com/watch?v=xLORU6ixBts
  Everything changed,
  young nigga came up,
  happened so fast,
  now a nigga famous,
  y'all niggas ass,
  guess you just ain't us,
  money don't last,
  how could you blame us,
  showed em what it is,
  showed em what the game was,
  now they want a hand out,
  never did a thing for us,
  now that I'm a standout,
  I'ma make em pay for it,
  it's gon be a a man down,
  you get in the way boyy,
  I'm serious,
  that's point blank period,
* Stove
 https://www.youtube.com/watch?v=RiRXcKMPg_E
Yeah - they like how he get like that?
niggas thought they had the crown I took that shit right back -
I put myyyy -
family on to better things,
when the devil came for me I just told him real niggas never change,
everything lookin real good lately,
now we gettin to the money like we should baby,
wish they would hate me,
I love it when they see me shine,
I'm in my prime, this aint no mistake it's by design.
rapper wanna see my dyin I'm like fine shoot ya shot.
If you miss it's suicide, think I'm lyin, but I'm not.
cuz it's really do or die when it come to the fam,
I would really risk a lot to see them comfortable man,
so if you come for the man,
you better come with a plan,
heard these niggas talk about it never done what they sayin,
that's a whole lotta cap in dem four dollar raps,
all I do is cook the dope like a stove in the trap,
* Run It Up
https://www.youtube.com/watch?v=tvtifBkk_As
Oh you thought it was said and done,
niggas actin like I been doin this shit for fun,
sure it's been a blast killin these trash rappers I passed,
dropped out but still have all of my class,
now it's gucci sweaters and LVs,
now the groupies want to take selfies,
the devil workin hard, but my neck cold enough to make hell freeze,
so what the fuck is he gonna tell me guess we'll see.
the real heat is in your eardrum now,
my enemies is feelin real dumb now,
but somehow they still think I'ma come down,
from where I'm at tho, never that tho,
I black out on raps tho It's that dope,
and as far as that goes,
I feel like the last hope.
they be lookin for women instead of cash flows,
followers over brand quality - that shows,
but I aint here to preach,
I'm here to make sure my niggas can finally get some reach,
I'm tryna see em own things they aint gotta lease,
and soon as I get some more change, they gon get a piece.
cuz really it's all loyalty,
coming at the king'll get you fucked up royally,
I'm right where I was born to be,
niggas talk down when the money aint up,
that don't happen over here,
we gon run this thing up.

yeah - run it up run it up.
thumbin through the money feelin like we comin up,
finally finally,
lonely at the top, but that's where we tryna be.
x2
* Tell Me
https://www.youtube.com/watch?v=ma8Q082zg1A

Tell me I got it, even when I don't got it,
when I say I'm not the greatest you tell me I'm being modest,
tell me life aint decided by things we've done in the past,
you said that communication's the key to making it last,
and I asked
* Too official
https://www.youtube.com/watch?v=iN7RwGJ8RHM
Too official like I blew a whistle,
at the bottom nigga who was wit you?

I'm just here for the money man,
cuz this rap game shit is superficial.

got some cousin's that'll shoot a missle at you,
if you buggin like computer issues,


* Feels So Strange
youtube.com/watch?v=o6xUEnHyBfQ

I know I won't change
tellin myself that I'm ok
nowadays everything feels so strange
but I'm so damn high I don't feel no pain,

* Star To Me
https://www.youtube.com/watch?v=b1F29fQ6Otc

No matter how far you go,
no matter how high you climb,
I'll always be your number one fan,
you're a star - to - me.
* Untitled
Uh - first off if the boy burst off then you the worst off,
now they askin me how much a verse cost,
better check the hearse cost,
this that diggin up dirt talk, that,
funeral music who new that this shit would work dawg,
they be tryna
* 16's perfected
https://www.youtube.com/watch?v=-FvDWgipMo0&list=RDdZKxxnOE8Wc&index=4
I feel like,
this is my callin,
I like women, and,
I like ballin so
I go all in the studio fallin asleep,
tryna put my heart on a beat,


which means I'm left with,
16's perfected.
* Quarter Pound
  https://www.youtube.com/watch?v=RiRXcKMPg_E&list=RDdZKxxnOE8Wc&index=5
Now my neck lookin like it's bout to freeze,
they like geeze,
now my whip, don't got keys,
you aint this,
nigga please check the steeze.
like a quarter pound, on my q's and my p's.
dot my i's, cross my t's for the cheese.

uh - big paper,
I ain't even tryin,
cop it if I like it baby,
they like what you buyin?
I'm like everything.
that won't ever change.
still a skinny nigga,
but I rock a heavy chain.
let it hang cuz my jeweler told me people gotta see this,
now I be like fuck it, I don't tuck it, they gon pree dis,
we don't do adidas, new balance what my feet is.
top guys, mob ties, I feel so elitist.
she is - tellin me how she need this,
sorry I don't believe it,
gimme brain like a genius.
then make her run it back,
like that - shit was a remix.
then I hop in the cleanest,
whip that you ever seen it's,
probably missing a top but,
really that is not the,
only configuration I press a button it pops up.
they is not us, and that's why these niggas hatin on me,
iced out,
bitches skatin on me.


* Matter
Yeah - just when I thought,
Everything that could make me happy could just be bought
I saw - that what I sought wasn't true,

fought
the only thing that saw me through that darkness was you
caught was the flu
* Mike
https://www.youtube.com/watch?v=1lsxARhkPjI
Damn I feel like Prince,
Man I feel like Mike,
Moonwalk on these niggas,
man I think I might,
diamonds dancin across the room,
and I know you see them hoes gleamin,
I been smokin on super thriller I'm smooth criminal leanin.
* On My Way
https://www.youtube.com/watch?v=q1gGz8mtzTU&list=RDRiRXcKMPg_E&index=4
ooooh, I'ma run it up that's what I do,
they wanna hold me back till I can't move no mo.
on my way and I can't fuck wit you no mo.

They gon hate me till I die I know,
just bury me with all the money when I go,

my pockets so swoll,
didn't have to sell my soul, aye
that's a fact,
heard yo track,
that shit's wack,


* All I know
https://www.youtube.com/watch?v=A6FeucVAfbU

This shit is all I know,
this shit is all I know,
* Untitled
I'm - lookin at my life through the lens,
of a nigga that, might do a benz,

it'll probably be a coupe see,
cuz I remember ridin through the hood in a hooptie.

2 - 3 niggas deep one loosie.
recitin the writin's in my loose leaf.
thinkin -

one day - i'ma be - that rap nigga,
fuck school, fuck a backpack nigga.

I'm finna blow up.

* Better now
Coulda been inside the ground
All my diamonds shinin now
No more buses bitch I'm drivin now
foreign wheels slidin now.
nigga thank god.
nigga thank god.
they wanted to see me fail but I can't god.
had to do it by myself fuck it thank y'all
cuz I'm better now.

Shit is not the same now my chain got hangtime,
* Shame
https://www.youtube.com/watch?v=ORiMPxP0f1U
since you been back it aint been the same,
I told you it's over you think it's a game,
you tryna redo it rekindle the flame,
shit is a shame shame shame
I been relaxin, doin my thang,
I haven't had you all on my brain.
you sendin me texts,
sendin me blame,
shit is a shame shame shame.

First off you know I aint the one,
ok ok being with you was fun,
but no way yo way was the way that would work,
hit me up I'm busy you go bezerk,
call my phone all on some bullshit,
you know I am not the nigga to fool wit,

bridge
and I don't got the time for it, no
gotta keep my mind on my dough,
... I guess that's not enough,
.... that shit is tough

* More
https://www.youtube.com/watch?v=fqhesZOixec

They said boy, chase some goals.
Go after yo paper faithfully don't chase these hoes,
the ones that try to expose you gon say that they yo bros,
friends turn foes,
that's just how it goes,
ten toes planted until I'm a ghost got damn it,
never seen defeat so,
I don't understand it,
all of it's like I planned it I promise,
I seen it comin,
Nostradamus or somethin no commas I keep it runnin,
I don't see how they frontin and talking bout bein next,
honestly how I'm stuntin this shit is like bmx,
so thangs is lookin better, especially the checks,
big body whips it's best for me to flex,
good smoke so don't expect for me to stress,
when I been getting right and my opps is getting left,
who pressed, you see I'm blessed nigga that's for sure,
got enough but it's not enough,
nah - I need more.

they don't gimme that I'ma take that till they kill me
real nigga I can't fake that do you feel me,
young nigga with the some old money but I still need more,

that's why I buy everything in store,
fuck you think I came here for?
nigga my whole family used to be poor now we livin like dons,
my dawgs went x-con to icon,
busses to teslas,
fuck can you tell us?
this is why it takes so much to impress us,
you cuffed her, I left her.
bustin her successor,
ring on my pinky is buff as a wrestler,
money like it's 25 lighters on my dresser,
bro said go head take everything if they let ya,
oh yeah oh yeah so I'm applyin the pressure,
till a nigga lyin in a stretcher.
who fresher? I'm smokin in my pajamas, hugh hefner,
you not talkin dollars ooh that's the, shit I don't like,
on my Chief Keef,
car so big that when I back it up that shit go beep beep,
I - fit in it neatly,
seats beneath me,
italian leather racing,
never left the states but the whip's from a different nation,
hunnits in suitcases, ones on the floor,
got enough but it's not enough,
nah - I need more.

delicacies we eat those

...accept nothin lesser
...and that's just the

atch how I do this,
never been the way you is,

* Would You
https://www.youtube.com/watch?v=5B60QxeKaNI&list=RDVasvd8-n75I&index=2

Would you run up on a hoe for me -
would you hold dope for me?

would you go all the way bonnie and clyde,
run up in the bank and tell em hit the flo for me?

* Crazy
https://www.youtube.com/watch?v=WQSfXKn_uAs

Yeah - this shit go crazy.
* Money Come
Money come - money goes,
fuck it that's ok cuz we gon get some mo,
* Pop
We just tryna get rich ya know,
you aint never seen nothin like this before.
touchdown my city whole block go pop.
know they hate that but it's not gon stop.

damn - that's a whole lotta cash in the safe,
can't even fit the stash in the safe.

some niggas switched sides on me that's just the breaks,
you won't ever get it if you gotta ask what it takes.
and I
never had to ask for shit.
I'm really that nigga you could ask your bitch.
she gon probably tell you oh yeah he's like, wow.
and that's why she rather be wit me right now,

lifestyle looking like I sold dope,
tryna make up for them days I aint' have no hope.

now a nigga flexin.
car george jetson.
weed all purple.
bad bitch blessin.

she from colorado but she ride it like a Texan
text messages tellin me you are out of the question.
but we don't really trip on that,
got a whole lotta drip she could sip on that.

hook x2

damn - that's whole lotta ass for her waist,
I let her push the jag for the day,

dem niggas switched sides I just laught in they face - uh,
headed to the bank with a bag fulla paper,

gotta nigga feelin like I made it now,
she called me I laid it down.

don't know why you callin her your lady now
she belongs to the game can't save her now.

bus round town in a what the fuck is that,
one touch, top down, tuck it in the back

smoke so loud pack bumpin out the sack,
that's the same shit my dawg had jumpin out the trap,

livin wild cuz really we never had shit,
this is for them niggas who thought I was gon be average,

now I'm gymnastic money doing a backflip,
off of vacation and back on they asses.

* O.D.
https://www.youtube.com/watch?v=m_vfKuTlHkk
they say - they don't even know me no mo
money got me goin O.D. oh no
will he ever be the same now pray for me,
but keep the negativity away from me.

Yeah - that's real though,
I am me - don't give a fuck bout how you feel bro.


talkin on the pillow


* Hate
https://www.youtube.com/watch?v=lmMDJMjhkvM
Do you hate me cuz?
I been killin tracks,
spillin facts,
make a nigga say that he ain't heard no shit as real as that?
feelin that - maybe I'm ahead of my time, or am I late?
am I just somebody that rhymes,
or am I great?
obviously the latter matter fact on this ladder I am top rung.
rappers hotter than me there is not one.
ya'll funny dudes 22's I'm shotgun,
runnin through whichever one of you think they got one on me,
awfully confident y'all be,
brush my shoulders dust that shit off me,
time is money, and my times costly.
foreal, you don't want see that Bill like Cosby.
I be on something that these niggas do not be.
can't control-c control-v copy paste me.
you not me. one of a kind.
race me ane you always gon be runnin behind.
lately I been feelin like I'm truly the shit,
AC bro I promise I'm as cool as it gets
rank me with the greatest in this musical shit,
cuz They see now that everything I'm doin is lit -
hate me cuz they see all that I did on my own -
take me to your leader I will sit on his throne.
the top is, where I belong, I consider it home.
used to love me now I made it and the feelin is gone,
they say.

hey, I'm on the next day,
no stoppin the money them checks say press play,
I guess they just hate cuz I do not quit,
these rappers doin the most, but they do not spit.
I drool, I rule, lines drew on stick.
like dude do you listen when I do my shit?
stay true to myself no matter who I'm wit,
keep it money over bitches fuck 2 x 6,
mama said you could be anything but you not this,
I murder rappers boy don't make me add you to my list,

when it comes to music this the shit I'm too nice with

ewing and knicks
so when I drop, I probaly won't see you for a bit -
cuz I'm gone -

* War
It's a war going on outside no man is same from,
some of us fighting for love, others hate, some
of us is in it for reasons unknow,
but demons have shown to get worse if you leave em alone,
we out here exercising,
* shook up
youtube.com/watch?v=UbrFl5niKFs

I got em shook up,
salty from the saucy shit I cook up,
it aint' too hard to find me, nigga, just need to look up.

but look at how far it took us
* Antifa
https://www.youtube.com/watch?v=MYoNrIUOwJE
I see cop,
he say stop,
I don't move,
pop pop pop,
body drop.
then when they wonder I got my glock,
* Me
https://www.youtube.com/watch?v=g4jKzA7wtqs
Look in my eyes,
see the truth I reveal,

In this booth I could kill,
any goofy that still think he could run me,

don't want me,
bro trust me,
I'm so hungry,
no tellin what I'll do for this meal,
got street niggas that I grew up with and they down to shoot for this bill,
we don't even really talk bout that, we more bout business,

* Summertime Sunshine
https://www.youtube.com/watch?v=jyoQu_qxtfE
My summertime sunshine,
you what I call, the colors of my fall,
with you in the winter it don't feel so cold at all,
yeah you make me sing, like it's late in spring baby -

baby can we talk birds and bees,
forest fires

burn some trees

* Known
Niggas should knowwn I was never gone I was really sittin low, (I was really sittin low),
I been on the phone like I'm doing shifts in the trap, but I'm not, it was really give and go.
got me in the zone, like a 2-3, like 2-3.
your man don't do it he a goofy,
got em all down in this battle royale,
nigga I'm just tryna land where the loot be.

* Quarantine Twerk
  https://www.youtube.com/watch?v=dK_FfA3nT4I

  Got yo mask on you can't take a chance,
  rub yo hands together if you countin bands,
  if you alone in yo house, puttin in work,
  2020 was a jerk, do the quarantine twerk.

  yeah yeah yeah yeah yeah
  where they at? over here? over there.
  stay from round me keep your energy out my air.

* Juice
  https://www.youtube.com/watch?v=nhfVbmlIqFk
  Who are you? Tellin me who I can be.
  Tell the truth - I give a fuck what you believe.
  I got the juice -

* Chasing Signs
  I find myself drifting away sometimes through space and time,
  chasing signs, wandering with no place in mind,
  take this blindfold from over my eyes so,
  I can visualize hope,
  let me give you the gospel.
* Never like us
  Who can I trust?
  Everybody tell lies,
  to put on disguises,
  even when I tried,
  so hard to vibe, I wasn't surprised,
  it was never like us.
* When you see me
  Believe me, believe me
  you gon be mad when you see me.

  Now that I'm poppin.
  They all be callin my phone.
  they see what I'm coppin,
  now they won't leave me alone.

* I feel fine
  Take me to that place I know where,
  I don't need nobody,
  just me myself and I, a drink and a swisher or two
  Cuz that's the only place I know where,
  I can be somebody,
  cuz anytime I'm in my right mind,
  I only think about you.
  Here I go,
  lately I just drink and get high so,
  much you probably thinkin I'm out of my mind,
  but right now I feel fine.
  Here I go,
  Dancin with the demons in my soul,
  drownin all yo memories out of my mind,
  so right now I feel fine

* KingPin
  Mama told me boy when gon grow up to be a man,
  Understand, you gon have to put some dollas in you hand,
  Cuz yo family's expecting you to stand up and plan for they future,
  you can be a rapper a producer after you get used to,
  holding down a job,

  I'm just focused on blowing up, blowin down cigars,

* Shine
  Shine bright lil' man, shine bright.
  You deserve all of your time in this lime light.
  'member everything that shines isn't made to chase the girls,
  and if you can change your mind, you can change the world.
  lil man' shine - bright
* Too Real
  Quarter million without rap, who doubt that?
  doin this since flag football out back,
  sunrise elementary,
  one eye on my money,
  and one eye on my enemies,
  somehow, all my energy -
  came back positive,
  nigga aint that obvious,
  and this my canvas I paint like Dali it's,
  up for interpretation but fuck if you surface hatin,
  let's dig deep,
  they want me gone I gotta be six feet,
  dirt nappin,
  but let's reverse, that's when my birth happened,
  poppe out spittin a verse I came in this earth snappin,
  earth-shatterin, words spatterin, when I speak,
* No Time
  https://www.youtube.com/watch?v=yWsLWgFqEpo

  Me and my thoughts get along now,
  everything is gone now,
  I'ma write a song bout you-ooo.
  that's what I'ma,
  yeah that's what I'ma, uh, yeah

  travel on my own now, home bound,
  on a different road now, wish you could have slowed down too.
  enjoy the view,

* Gotta be
  https://www.youtube.com/watch?v=k9K7xszaQzo
  Who do I - gotta be -
  for you to see -
  that I am the one for you -
  don't make me run for you -
  Who do I - gotta be -
  for you to see -
  that I'm thaaaat guy.

  fallin apart, wearin my heart,
  all on my sleeve,
  tellin my soul, follow my lead,
  I'm telling you that you all that I need my -,
  niggas is tellin me that I be trippin you never gon be mine -,
  I don't be listenin,
  I just be picturin, livin the dream life
  by yo side with that white picket fence,
  and that two car carage where you park yo lil benz,
  that I bought you cuz I know you gots to stay clean,
  wanna make these daydreams as real as they seem, so -

  chorus

  I be online seeing your I - G when you live,
  talkin bout you need a man in your life,
  I send a message and you don't reply oh,
  I wonder why,
  I see the guys you check on and,
  I feel like I could flex on them -
  you could stand me up next to them,
  like what do they got that I don't,
  tell me and I'ma go get it as soon as I can,
  and girl if you thinkin I won't,
  send a reply to my message and give me a chance,
  and I'll be waiting for that notification bell to say,
  I have a new message from you, and you have always felt this way,
  about me too, how bout we do, something bout this lil connection,
  cuz right now it's one way but one day we'll find our direction,

* Check
  https://www.youtube.com/watch?v=PRt5C-WBJoM

  Whoa, I just ran through a check,
  yeah it's spent, took the rent, put that shit on my neck. Huh?
  yeah I don't need ya respect

* Slave Ship
  https://www.youtube.com/watch?v=fxxytriq3p8
  Come take a ride on my slave ship,
  Come take a ride on my slave ship,
  you could have everything you ever wanted if you let us handle the basics,
  if you want more you gon chase it, and chase it, and chase it,
  .....

  Uh - Prada on me got me lookin fresh,
  bought it Friday, watch me buss a check.

  so these hoes know I got dough,
  next friday Ima cop mo,



  Uh - Louis on me got me lookin rich

* need no love
  https://www.youtube.com/watch?v=Ftu4QfrUdVY

oh no,
you can't have/get that baby girl I'm so solo, oh yeah
I been up too long don't trust these hoes no mo, nope nah,
that's the difference between them and me because, um yeah
I got money baby I don't need your love


in a spaceship,
damn my seats so plush,
tell niggas eat my dust,
I be so up,
I don't really feel no pain,
I don't really need no love,

and these hoes what? tryna come be my wife?
no - adios slut,
I peeped yo bluff,
you shoulda thought about that for you tried to play me so tough,

ain't got no time,
even though the watch on shine,
shorty you is not that fine,
don't cross that line,
I can't put your first,
that's the last thing on my mind,
I'm on my grind like I'm tryn stand still on a handrail, if you know you know
real nigga, I don't dance much,
but these vvs's do si dos,
knew back when I broke and smokin, optimos from the grocery sto,
one day, even if came down to the gun play, niggas wouldn't be broke no mo,
now look at us - aww,
flow crack I cook it up, hard,
I see you niggas ain't been round money
and you not fuckin up ours,
aint' no use cuffin that broad,
told her we fuck and that's all,
she aint been up for that long,
can't put no trust in that dawg,
I got my mind right,
I told her get her mind right,
she must not know how I'm like,
she say she want this lime light,
I told that girl

like - I don't need yo pussy why you fussin,
don't you that come a dime a dozen,
and I ain't payin nothin -
dollas only thing that's worth discussin,
tryna make this shit somethin it wasn't,
told her she could roll like some avalanche snow,
I'm too cold for yo heart hoe,


* So So
https://www.youtube.com/watch?v=e09tgq9APT4

Told my bitch let's get wavy,
you leave me then you crazy,
always been fuck you pay me,
play me you ghost like swayze,

I take care my whole family,
everything else is gravy,
now I pull up in that spaceship,
teachers said they can't save me,

please just stay out my way,
I ball but don't think I play,
nigga never been much of a shooter,
please don't make this my day.

I might step back hit that jumper,
don't watch yo life fade away,
I might hit once then I dump her,
I bounce like I'm 808,

big whip slip slide like I'm Trick,
you catch me slippin? ain't no way,

* Go
https://www.youtube.com/watch?v=d_HDC-LXV7s

I don't even rap nigga.
uh.
uh.


back when,
puff had sean jean fashion,
I was just rappin
killin these niggas with no compassion,
this just somethin I wrote in passing,

* Aint it beautiful
aint it beautiful? Yes it is.
niggas act like they do not know what a blessin is.
I'm just checkin in cuz I want my next-to-kin ok,
but I think his favorite letters f and n,
so hey, if you guess I couldn't relate, guess again.
I can understand turnin 5 into 10,
double back tryna multiply it again.
I'ma need a trophy when I get the win,
and my whole team finna be stuntin.
If we can't all ball, this shit don't mean nothin.



man it's beautiful - I could turn a 5 to 10 double
back and multiply it again and cuzI get the win -
I don't need a trophy,

