:PROPERTIES:
:ID:       B7478D2A-B3A0-4F6B-A2A1-3BE040FAB4C1
:END:
#+title: Why I Still Use Emacs
#+date: 2024-06-10
#+hugo_custom_front_matter: :garden_tags '(emacs ergonomics productivity)
#+hugo_custom_front_matter: :status growing 

[[id:E2D60F17-89E2-4148-8DAD-587B69BF01DB][Emacs]] [[id:811A413C-B35B-42E8-8C00-F7796FD3F439][Ergonomics]] [[id:3DA6243F-8CD3-4EC1-9444-ED1395D1EFD7][Productivity]] 

* Why I Still Use Emacs
** The Ergonomics Bug

My Emacs journey began with one simple desire; to make ergonomics a first-class
citizen in my work day. 

It didn't start with Emacs, though, it started with some changes to my workspace
like a better chair, a split keyboard, and a better mouse.

As the ergonomics rabbit hole got deeper, I continued finding new ways to tweak
my setup for better health and more productivity.

I can't remember where it was, but I came across a discussion where someone was
praising the value of "Spacemacs", a text editor which is based on Emacs
and prioritizes ergonomics and ease of use.

At the time, I was a VS Code evangelist to the point of having written my own
themes and plugins and I couldn't see myself ever leaving the VS Code community.

Still, I was interested in making my coding experience more comfortable and productive,
so I installed Spacemacs to give it a test run.

That test run would become a life-changing journey into the world of modal editing,
note taking, productivity, and so much more.

** Work At the Speed of Thought

"Modal Editing" is a term used to describe text editing in different "modes".

By default, editors like VS Code have one mode - edit mode. When you place your cursor
in the text editor, you can just start typing to see characters appear.

In modal editors, you might have more than one mode. In Emacs the two most common are "Insert mode",
which is the mode that allows you to insert text, and "Normal Mode", which is a mode that has commands
for navigating whatever text you're currently looking at. 

At first the idea of modal editing sounded terrible. Why would anyone want a different mode
than the one that lets you insert text into the editor?

Well, the navigation of on-screen text is where the ergonomics of modal editors truly shine. Instead of reaching 
for my mouse every time I need to highlight something, I can do it from my keyboard within a few key strokes.

When I need to jump to a specific line, Emacs can list letters in the margin that correspond to each line,
and typing one of those letters jumps me right there.

This allows me to "work at the speed of thought" since the actions required to edit text take less context
switching.

** Come For the Speed, Stay For the Productivity

Learning how to work with a modal editor was a huge boost to my productivity, but Emacs comes with
a killer feature which boosts productivity to unheard of levels; Org mode.

Org (short for organization) mode is a suite of packages that allow you to use basic markdown to write, organize,
schedule, measure, and plan pretty much anything.

This blog is written and published in Org Mode. I have an entire second-brain note taking setup that lets me
quickly capture and connect ideas and thoughts throughout the day. I manage all of my reading citations with
an Org Mode plugin for Zotero. I've seen folks manage their finances in Org Mode.

I'm able to review my calendar, schedule tasks, run pomodoros, clock in and out of activities, and set reminders
all without lifting my fingers from the keyboard.

At this point I essentially run my entire life out of Emacs and Org Mode, and it gives my brain a chance to offload
so much of the task management burden that comes with professional software engineering.

