:PROPERTIES:
:ID:       651ED9AE-CB40-4A56-B4E4-C1DE8AA0F252
:END:
#+title: On Effectively Scaling Engineering Teams
#+filetags: :notes:
#+hugo_section: notes
#+date: [2025-01-06 Mon]
#+hugo_lastmod: [2025-01-06 Mon]
#+hugo_tags: noexport
*Link*: [[id:CC58D5BD-1B6F-4464-AFC2-C805ED1B425D][Engineering]] 

** How do you scale engineering teams and culture? 
- Each component in a system shoulnd have a single, well-defined
  responsibility and there should be minimal dependency between other
  components in the system.

- Communication acrorss teams should have low bandwidth, anb be
  limited to when the teams are working on new ideas or building proof
  of concepts, as that requires a collective and broader outlook
  towards solving problems.

- High-performing engineering teams are built on "services for teams"
  not "teams for services". Every service or component should be owned
  by exactly one team. In the event that a service or component is
  shared between multiple teams, one of the teams should claim ownership
  
  [[https://leaddev.com/velocity/8-principles-effectively-scaling-engineering-teams][reference]]



