Darrell's User Manual
** Me In a Nutshell
   I'm an outgoing, ambitious personality with a passion for GSD and a high attention to detail.

** My Style
*** I live and die by the roadmap - I don't mind agility & flexibility, but having a well-defined mission with clear goals is my preference
*** I enjoy learning new things constantly - let's dive into some uncharted territory together!
*** I like to dive into deep work, but am also always open to pairing & collaboration!

** My Values
*** Transparency - I like to be 100% honest about life, work, and my feelings. WYSIWYG!
*** Candor       - related to transparency, I like to tell it how it is and hope folks do the same w/ me.
*** Owernship    - I want to make sure everyone has a stake at the table.

** How To Best Communicate With Me
*** Come prepared! Having an agenda will help us both know what we expect from our collaboration.
*** I can get a bit "philosophical" so please feel free to pull me back down to earth when my thoughts get lofty.
*** I get excited about talking through ideas and might jump around a bit - please wrangle me!

** What People Misunderstand About Me
*** I tend to have an overabundence of positivity, but that doesn't mean I'm not taking your feelings or situation seriously - I just like to smile!

** What I want to Improve on as a human being
*** Listening. Sometimes I talk too much.
